# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d95f13a15de7c26eb2f199831bf3460dff2672afd2b6a0375fbd9dfb954d54f1ae6edf215d9f21a5bf7478eb087e8de8e82ea9260e58dc31365bd2069e5589bb

test:
  secret_key_base: aae1b6e2c57f2516a5b6cabcb55414208e6fcbfe97168795e5d594cff5447ebe227445256c8becc6d1e9a8912a8e63dea144c3c62d3035ece23addb8678c3d22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
